---
title: "Beauty Contest"
author: "Matteo Ploner"
date: "`r format(Sys.time(), '%d %B, %Y')`"

output:

  prettydoc::html_pretty:
    theme: leonids #hpstr #tactile #hpstr
    highlight: github

  html_document:
    number_sections: true
    toc: true # table of content true
    toc_depth: 3  # upto three depths of headings (specified by #, ## and ###)
    toc_float: true
    theme: cosmo  #united; paper; cerulean
    highlight: tango  # specifies the syntax highlighting style

  ioslides_presentation:
    toc: yes
    toc_depth: 2
    incremental: no
    smaller: no
    widescreen: yes
    duration: 90
    self_contained: yes

  slidy_presentation:
    footer: "FOOTER"
    duration: 90
    self_contained: yes

  beamer_presentation: default

  revealjs::revealjs_presentation:
    reveal_options:
      slideNumber: true
      previewLinks: false
      controls: false
      navigationMode: linear #grid, default
    theme: sky #“default”, “simple”, “sky”, “beige”, “serif”, “solarized”, “blood”, “moon”, “night”, “black”, “league” or “white”
    highlight: pygments
    slideNumber: true

  pdf_document:
    keep_tex: true
    number_sections: true
    df_print: kable
documentclass: article
fontsize: 11pt
geometry: margin=1in

#css: PATHto/.css
#bibliography: PATHto/.bib
---


# Sample  {.tabset .tabset-fade .tabset-pills}

```{r , echo=FALSE, warning=FALSE, message=FALSE, fig.height=4, fig.width=4, fig.align="center"}
library(tidyverse)
library(knitr)

setwd("/Users/matteo/Google Drive/WORK/insegnamento/VARIE/smart_BEEjS/lectures/1_method/data.csv")

# Spectators
d <- read_csv("beauty_contest_2020-06-11.csv") %>% filter(participant.time_started > "2020-06-11 12:00:00 UTC" )
# participant.code
# player.display
# player.guess
# group.best_guess
#subsession.round_number
```

# Individual observations


```{r , echo=FALSE, warning=FALSE, message=FALSE, fig.height=9, fig.width=12, fig.align="center"}
d %>% select(participant.code,  player.display, subsession.round_number,player.guess) %>%
ggplot(aes(x=subsession.round_number,y=player.guess))+
geom_point()+
geom_line()+
facet_wrap(.~participant.code)+
scale_x_continuous(breaks=seq(1,3,1),minor_breaks=seq(1,3,1))+
theme_bw() +
labs(title="Guesses",
    subtitle="By individual",
    y = "Guess",
    x= "Round",
    fill="")+ # labels
theme(legend.position="none",
     axis.text=element_text(size=8),
     axis.title=element_text(size=14,face="bold"),
     axis.text.x = element_text(angle = 90, hjust = 1,vjust=0.5)) #axis
```

# Aggregate Choices {.tabset}

## By round

```{r , echo=FALSE, warning=FALSE, message=FALSE, fig.height=9, fig.width=12, fig.align="center"}
dt <- d %>% select(participant.code,  player.display, subsession.round_number,player.guess) %>%
group_by(subsession.round_number, player.guess) %>% count() %>% na.omit()

stats <- d %>% group_by(subsession.round_number) %>% summarise_at("player.guess",~mean(.,na.rm=TRUE)) %>% mutate(win=player.guess*2/3)

ggplot(dt,aes(x=player.guess,y=n,fill=player.guess))+
geom_col()+
facet_wrap(.~subsession.round_number, nrow=3)+
geom_vline(data=stats,aes(xintercept=win),color="red4",linetype=2,alpha=.5)+
geom_text(data=stats,aes(x=win+1,y=0,label=round(win,1)),color="red")+
scale_x_continuous(breaks=seq(0,100,5),minor_breaks=(seq(0,100,1)))+
 theme_bw() +
 labs(title="Guesses",
     subtitle="By round",
     y = "Freq",
     x= "Guess",
     fill="")+ # labels
theme(legend.position="none",
      axis.text=element_text(size=8),
      axis.title=element_text(size=14,face="bold"),
      axis.text.x = element_text(angle = 90, hjust = 1,vjust=0.5)) #axis
```

## By treatment

```{r , echo=FALSE, warning=FALSE, message=FALSE, fig.height=9, fig.width=12, fig.align="center"}
dt <- d %>% select(participant.code,  player.display, subsession.round_number,player.guess) %>%
group_by(player.display, player.guess) %>% count() %>% na.omit()

stats <- d %>% group_by(player.display) %>% summarise_at("player.guess",~mean(.,na.rm=TRUE)) %>% mutate(win=player.guess*2/3)

ggplot(dt,aes(x=player.guess,y=n,fill=player.guess))+
geom_col()+
facet_wrap(.~player.display, nrow=3)+
geom_vline(data=stats,aes(xintercept=win),color="red4",linetype=2,alpha=.5)+
geom_text(data=stats,aes(x=win+1,y=0,label=round(win,1)),color="red")+
scale_x_continuous(breaks=seq(0,100,5),minor_breaks=(seq(0,100,1)))+
 theme_bw() +
 labs(title="Guesses",
     subtitle="By treatment",
     y = "Freq",
     x= "Guess",
     fill="")+ # labels
theme(legend.position="none",
      axis.text=element_text(size=8),
      axis.title=element_text(size=14,face="bold"),
      axis.text.x = element_text(angle = 90, hjust = 1,vjust=0.5)) #axis
```
